### PR TITLE
rm npmignore, use explicite whitelist in package.json, rm legacy scss

### PR DESCRIPTION
**Pull request by MrTango**

### CODE REVIEW

**Comment by MrTango** [comment]
this fixes #305

**Comment by MrTango** [comment]
@mauritsvanrees after review, could you do a npm release please or should i do it?

**Review by mauritsvanrees — APPROVED** [review]
Looks okay to me. Thanks.
I can do a release.

**Comment by mauritsvanrees** [comment]
I have released beta 4.
...
Seriously? Did I only approve this and not merge this?? Need more coffee.
I will do another release.

**Pull request merged**
