### PR TITLE
change contrast for WCAG

### PR DESCRIPTION
**Pull request by polyester**
most of these are fairly minor, but there's two with big visual changes:
- changed ```@plone-sitenav-link-hover-bg from #9abdd6 (light blue) to #757778 (gray). There is *no way* to pass the contrast checks otherwise, without resorting to really dark blues, which looked weirder than gray.

- a light underline under links in the #content-core. This is to satisfy http://www.w3.org/TR/WCAG20/#visual-audio-contrast-without-color, which we cannot do without underline unless we change the whole color scheme, see http://webaim.org/blog/wcag-2-0-and-link-colors/

### CODE REVIEW

**Comment by vangheem** [comment]
I doubt this will cause any test failures but will run them before we merge: http://jenkins.plone.org/job/pull-request-5.0/509/

Is there anything we really need to review here or are these sort of necessities? I'm fine with what you described fwiw...

**Comment by polyester** [comment]
you can argue about the gray in the sitenav-bg; but seriously any shade of blue that would qualify (and I've spent more time on http://contrast-finder.tanaguru.com/ than is healthy) looked crap. The gray for me was by far the best choice.

 All the others are necessities, but also not very visible (they include a contrast change for screenreader-only classes, now that's not something screenreader users will complain about, but it helps to automatically validate)

**Comment by vangheem** [comment]
@polyester I ended up reverting your PR.

I didn't review it well enough at first and once I tested it further I started noticing some places where these changes really affect the UI. Resource registries and folder contents for example.

I've created a new PR on a new branch you people can continue to work on: https://github.com/plone/plonetheme.barceloneta/pull/56

Can we find some designers to review and help out maybe?

**Comment by polyester** [comment]
Whoops. I went through all the standard portlets, but not the folder contents. I'll work on it more and see if I can engage Victor et al.

**Pull request merged**
