### PR TITLE
Issue 1017 - Center buttons on ordered selection lists

### PR DESCRIPTION
**Pull request by rodfersou**
closes https://github.com/plone/Products.CMFPlone/issues/1017

### CODE REVIEW

**Comment by rodfersou** [comment]
http://jenkins.plone.org/job/pull-request-5.0/343/

**Comment by rodfersou** [comment]
http://jenkins.plone.org/job/pull-request-5.0/347/

**Comment by rodfersou** [comment]
@pbauer @vangheem  green light here

**Comment by vangheem** [comment]
oops, now you have to rebase :)

**Comment by vangheem** [comment]
go ahead and merge after rebase though.

**Comment by rodfersou** [comment]
@vangheem rebased

**Comment by vangheem** [comment]
Thanks!

**Pull request merged**
