### PR TITLE
In rules prefer css selectors

### LINKED ISSUE #38: Avoid mixing CSS and XPath selectors on Diazo rules
Convert all or most unneccessary XPATHs to CSS so code is more homogeneous and at least with Vanilla Plone there's one less thing to learn.

The only place they *might* be needed is [inside the `test` attribute of the  `<xsl:if>` tags](https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/rules.xml#L47-L50).

### PR DESCRIPTION
**Pull request by davilima6**
Fixes #38

### CODE REVIEW

**Comment by davilima6** [comment]
@bloodbare @vangheem: could you please review this?

**Comment by sneridagh** [comment]
It's fine for me. If @bloodbare or @vangheem have any issue with it I will merge it later.

**Comment by davilima6** [comment]
I just updated this PR after #40 #41 #42. @vangheem @pbauer @sneridagh Could you please review and merge?

**Comment by vangheem** [comment]
Everything looks fine. These are good changes. Thank you.

**Comment by davilima6** [comment]
Thanks! I hope they make it to Plone 5.

**Pull request merged**
