### PR TITLE
Discard duplicated ids for columns 

### PR DESCRIPTION
**Pull request by davilima6**
Closes plone/Products.CMFPlone#1105

### CODE REVIEW

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/496/

**Comment by davilima6** [comment]
The fail doesn't seem related. I don't know if I can trigger a new build on jenkins, though.

**Comment by jensens** [comment]
- login to jenkins
- go to http://jenkins.plone.org/job/pull-request-5.0/build
- paste url of this pr into the text-area input, hit buton build
- copy url of new build job in left column of jenkins and paste here as comment

**Comment by davilima6** [comment]
Thanks! http://jenkins.plone.org/job/pull-request-5.0/508/

**Pull request merged**
