### PR TITLE
Added a border animation to the alert boxes

### PR DESCRIPTION
**Pull request by klje**

### CODE REVIEW

**Comment by klje** [comment]
@jenkins-plone-org please run jobs

**Review by MrTango — CHANGES_REQUESTED** [review]
The changes need to be made in the scss file not in the compiled css file.

**Comment by MrTango** [comment]
please make a rebase from master and rebuild the css after. This way it should be mergeable without conflicts.
Pleas ping me as soon as you re done with that, so that we merge it fast.

**Review by MrTango — APPROVED** [review]

**Comment by agitator** [comment]
while working on another addon, I wondered why suddendly some headlines got bolder...
Screenshot 2021-08-16 at 18 49 49

and found the reason in this pr...

Sorry, had to revert this ...  @klje please revise your branch/pr

- don't globally style an a-tag from a component - only style components
- no eplicit color values
- check the nesting of your styles
- use variables from bootstrap wherever possible https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L1441 
- also check https://github.com/twbs/bootstrap/blob/main/scss/_alert.scss and https://github.com/twbs/bootstrap/blob/main/scss/_transitions.scss

if you need anymore input ping me in the classic-ui channel on wednesday

cc: @MrTango

**Pull request merged**
