### PR TITLE
Bootstrap 5.3

### PR DESCRIPTION
**Pull request by agitator**
We had a https://www.hackergarten.net and some time to work on it.
Tested it quickly and haven't found any issues on first look. It can be enabled by adding the `data-bs-theme="light|dark"` to the html tag itself or any other attribute.

I prefer the Javascript way https://getbootstrap.com/docs/5.3/customize/color-modes/#javascript which checks the media query `prefers-color-scheme` and also stores the selected mode to localStorage. 

Since we already have quite some logic in theme and `index.html`, I'd propose adding this functionality there. Not by default but with a howto in the documentation.

### CODE REVIEW

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Comment by rnixx** [comment]
Very nice, thank you. Should we bump version to 3.1 then?

**Comment by rnixx** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
Lets also have a look at the Migration documentation https://getbootstrap.com/docs/5.3/migration/ and see if we need to do something on our side. Especially importing `variables-dark` is missing here I think.

I would also recomment to wait until the 5.3 release is in a stable state before merging this.

**Comment by yurj** [comment]
The right place is a branch to play with it.

**Comment by petschki** [comment]
@yurj `bs-53` is the branch to go 👍🏼

**Comment by rnixx** [comment]
+1 for checking the migration guide.

I think merging is fine before BS 5.3 is final, we can also drop alpha/beta releases.

**Comment by rnixx** [comment]
Hi, after a short discussion with Hannes, one way to continue on this one could be:

- Merge #321 into `bs-53`
- Create branch `3.0.x` from recent master.
- Merge `bs-53` into master and drop a 3.1.0 alpha release.

Plone 6 then targets to `3.0.x` by default, while anyone is able to use the new features right away from pypi.

The same procedure might also be applied to https://github.com/plone/mockup/pull/1282

@petschki @mauritsvanrees @agitator @thet @jensens

**Comment by petschki** [comment]
That would be perfectly fine for me.

I'd do the same for for mockup and staticresources:

- mockup -> 5.1.0-alpha.1 with BS 5.3 support
- staticresources -> 2.1.0a1 with BS 5.3 support and a barceloneta version pin to `>=3.1.0a1`in `setup.py`

**Comment by rnixx** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Having this in new feature releases that go into Plone 6.1 sounds safest. I would be in favour of that.
The downside is that we would need to support two branches for all these packages, at least as long as 6.1 is not out yet.

See also the maintenance policy in the [release schedule](https://plone.org/download/release-schedule):
> Each minor release gets at least one year of maintenance support.
> On top of this, after the next minor version is released, there is an overlap of half a year where the previous release still gets maintenance support.

Technically we would support three branches: also the ones for Plone 5.2. But maintenance/development for Plone 5.2 has died down on these branches: last change of mockup and staticresources was from April last year, and Barceloneta even from 2020.

**Comment by mauritsvanrees** [comment]
I have added this and the PRs for mockup and staticresources to a new project Plone 6.1:
https://github.com/orgs/plone/projects/25/views/1
They are already in the Done state.

**Pull request merged**
