### PR TITLE
Remove SVG font

### LINKED ISSUE #357: Remove SVG fonts?
According to https://caniuse.com/svg-fonts they are deprecated and actively removed from browsers, only Apple browsers are still supporting it.

### PR DESCRIPTION
**Pull request by petschki**
fixes #357

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by gforcada — APPROVED** [review]

**Comment by gforcada** [comment]
Looks good, some conflicts need to be resolved seems 🙃

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
thank you @gforcada ... yes I've merged another PR meanwhile ... re-based and re-compiled the scss files again. will merge when green

**Pull request merged**
