### PR TITLE
Integrated plone.app.event styles and further cleanup.

### PR DESCRIPTION
**Pull request by agitator**

### CODE REVIEW

**Comment by pnicolli** [comment]
Hi 😃 
IMHO it would be awesome to explain what is changing here, mainly for two reasons:

- It's described as a breaking change in your changelog addition, so I think it's important to describe what you're breaking, since many people will use your new code in their future Plone installations. Also, I'm not a fan of introducing a breaking change as a minor version bump, but I'm not sure we have specific guidelines here about here.
- Having a breaking change together with other cleanup changes in the same commit makes it difficult to understand what's changing, and therefore to review the pull request.

My suggestion would be to separate the two things (change and cleanup) and/or to add a description to help readers understand what changed here.

**Comment by agitator** [comment]
Hey @pnicolli 
Your're right about the breaking change and versioning, moved it to new feature now ;-)
About the changes, as stated, I moved the styles that were still in plone.app.event here.
I also have overwritten the annoying border-bottom on a tags that comes from `#content-core a` and the weird extra identation in `portletContent`.
The rest is reformatting...

**Comment by thet** [comment]
@sunew tnx for fixing and merging!

**Comment by sunew** [comment]
@thet :)

**Pull request merged**
