### PR TITLE
Include SASS source files

### PR DESCRIPTION
**Pull request by datakurre**
LESS is and will be the master source for Barceloneta theme in Plone 5.x, but at Barcelona Sprint in May 2016 @albertcasado did create a SASS version of the theme. SASS source files would simply live next to LESS source files and would only add some weight for the package, but have not other affect.

Merging SASS files into master would help us to not forget it and probably make it easier to keep in sync with the official LESS one. Also, if anyone else would get into Webpack built themes, SASS files would be usable there.

### CODE REVIEW

**Comment by agitator** [comment]
how are those scss files generated and foremost updated?

**Comment by datakurre** [comment]
@agitator I'm not sure if @albertcasado used a generator in the first place, but I assume Barceloneta be stable enough that manual updates are not an issue.

**Comment by agitator** [comment]
if it's not done in an automatic way, sooner and probably not later we'll have to versions

**Comment by datakurre** [comment]
@agitator That's a risk to be consider in this pull :)

**Comment by jensens** [comment]
Please PLIP this, this is a massive amount of scss code we need to support and so has impact. 
So no merge without PLIP.

I'd prefer an automatic conversion too.

If automatic conversion does not work, I'd prefer a second standalone theme as an addon product, which then can port all changes in barceloneta to the ``plonetheme.barceloneta_scss`` outside of plone core.

**Comment by jensens** [comment]
cc @plone/framework-team

**Comment by datakurre** [comment]
@jensens, @agitator Thanks. I played with this enough that I can confirm that automated conversion is not really a lasting option. I believe, @albertcasado did the original conversion with automated tool, but then at least had to refactor, how font faces were generated. Also, I had to do minor fixed for grid definitions, import order, and make variables to be defined as "defaults" to make them overridable.

So, let's leave it to less2scss branch for now, until there's a real use-case for packaged SCSS theme. Git checkout works fine for webpack.

**Pull request closed without merging**
