### PR TITLE
Update footer rules

### PR DESCRIPTION
**Pull request by petschki**
remove colophon and copyright too, when not present in  content.

bump version to 1.10.0 because of breaking changes.

### CODE REVIEW

**Comment by jensens** [comment]
> breaking changes

if its really breaking, that would mean a 2.0.

**Comment by tmassman** [comment]
It's not breaking changes. It's just that the html placeholder we have in the template will be removed if the mentioned footer portlets are not available. So just cleaning up what I forgot.

**Comment by tmassman** [comment]
Also, @pbauer  already merged #163 which introduced the new html markup in the footer, and this is planned for the 1.9.2 release or, if we want to, a 1.10.0.

**Comment by jensens** [comment]
well, then lets be good semantic versioning citizens and increase to 1.10.0 and merge this

**Comment by petschki** [comment]
@jensens off topic: what about this flaky tinymce robot test? I've stumbled across this several times in 5.2 and now in 5.1 too ...

**Comment by Rotonen** [comment]
This particular one is probably a racecondition induced by browsers making more and more previously-sequential synchronous javascript asynchronous over time. Especially loops will get you.

**Pull request merged**
