### PR TITLE
fix padding in nested navigation tree

### PR DESCRIPTION
**Pull request by petschki**
and show icons always in tree (is there a reason why not?)

tree before (Plone 5.1)
bildschirmfoto 2018-07-09 um 14 56 11

tree after
bildschirmfoto 2018-07-09 um 14 56 40

this fixes https://github.com/plone/Products.CMFPlone/issues/1906

### CODE REVIEW

**Comment by agitator** [comment]
the hover looks a bit weird...shouldn't only the hovered element change?
screen shot 2018-07-10 at 17 45 40

**Comment by petschki** [comment]
@agitator yes you're right, but I didn't change the hover at all ... I can look at this ...

**Comment by agitator** [comment]
also the line underneath the 2 (must be the topline from 3) looks a bit weird, but not sure how to fix that...

ident just the content of the a tag?

**Comment by petschki** [comment]
well, that's what I tried the first time, but then you have to explicitly define every padding of every level ... I'll take a second look at this tomorrow and try to come up with a more elegant solution where the border keeps 100% width and the a tag gets indented as intended ... not sure right now how to handle this though ...

**Comment by agitator** [comment]
much better!

one more thing ... could you get rid of the > for the last item that has no further ul?

**Comment by petschki** [comment]
should we get rid of this? As for my understanding it's just an indicator for active level ... though a bit redundant with background and font colors ...

**Comment by agitator** [comment]
to me it always meant there's more to come on that level

**Comment by petschki** [comment]
last state:
bildschirmfoto 2018-07-12 um 13 42 04

**Comment by agitator** [comment]
not wanting to cause more trouble... ;-)

hover and selected style should be similar, similar background color and > only if there's more

and indicator for selected would be on the left side for me

**Comment by petschki** [comment]
funny gifsicle 😉
navtree

**Comment by petschki** [comment]
very last state
bildschirmfoto 2018-07-12 um 14 13 45

**Comment by agitator** [comment]
I shut my mouth now, looks good enough to me ;-)

**Comment by petschki** [comment]
@agitator @jensens anybody willing to merge this navtree CSS fix? I think this is better than the navtree version we actually have...

**Pull request merged**
