### PR TITLE
Add TinyMCE UI css

### LINKED ISSUE #307: TinyMCE UI styles are missing if not inline

### PR DESCRIPTION
**Pull request by petschki**
fixes #307 

does this need an upgrade step?

/cc @thet @MrTango

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by Rudd-O** [comment]
Needs registry upgrade step @petschki

**Comment by MrTango** [comment]
an upgradestep would make sense to load the profile.

**Review by jensens — APPROVED** [review]
LGTM, upgrade step would go to p.a.upgrade, so this one is ready.

**Comment by petschki** [comment]
@jensens so this commit (https://github.com/plone/plonetheme.barceloneta/pull/308/commits/abffc5022a168e53f154d9f54abbb7f742a8939c) should go to p.a.upgrade? Do I need to increase the metadata version here?

**Comment by jensens** [comment]
You can keep it here, but call it from p.a.upgrade, so one does not need to do an extra step besides the normal upgrade.

**Review by MrTango — APPROVED** [review]

**Comment by Rudd-O** [comment]
Please note this change folks:

https://github.com/plone/Products.CMFPlone/pull/3638

**Pull request merged**
