### PR TITLE
fix styles for '#portal-header'

### PR DESCRIPTION
**Pull request by gvizdyk**
Updated style for the '#portal-header'

### CODE REVIEW

**Comment by gvizdyk** [comment]
@vangheem, @jensens  Could you accept these changes? I deleted unnecessary styles that were duplicated.

**Comment by jensens** [comment]
Thank you for your contribution! In order to merge this Pull Request the Plone Foundation requires a Contributor Agreement from you. I can not find you in the list of contributors. This may be by accident and we forgot to add you there or because you never signed the contributor agreement. In first case send an e-mail to agreements@plone.org referencing this issue. In second case please visit https://plone.org/foundation/contributors-agreement and follow the instructions to become an Plone core contributor. Sorry for any inconvenience.

**Comment by gvizdyk** [comment]
@jensens just re-sent the copy of signed agreement to agreements@plone.org.  Original was sent 05.05.2015 to assignments@plone.org

**Comment by ableeb** [comment]
@gvizdyk, @jensens Your Plone Contributor's Agreement has been processed.  Thanks!

**Comment by gforcada** [comment]
@ableeb great to hear that, @gvizdyk welcome to Plone as a core contributor!

Would you mind rebasing and pushing the branch? It seems it can not be merged without manual effort.

**Comment by gvizdyk** [comment]
Thanks for adding me to Plone band ;)

@gforcada the merge is ready - I merged branch with master, there are no conflicts.

Should I make pull requests or merge changes myself in future?

**Comment by gforcada** [comment]
@gvizdyk as a rule of thumb always make pull requests and ask for a review before merging.

As for this one, unfortunately is not my area of expertise, so let's see if someone else can review and merge.

**Comment by gvizdyk** [comment]
@vangheem, @jensens, could you merge my pull request?

**Comment by vangheem** [comment]
@gvizdyk can you explain what you're doing more? Maybe provide a screenshot of before and after?

Also, can you squash your commits?

**Comment by gvizdyk** [comment]
@vangheem there are no visual changes. 
This code just enhances and optimizes styles, in particular:
 * deleted unnecessary styles that were duplicated.
 * simplified selectors

I squashed commits into one.

**Comment by vangheem** [comment]
Sounds good, thank you.

**Pull request merged**
