### PR TITLE
Fix CSS issue with new dropdown menu for 2nd level navigation 

### PR DESCRIPTION
**Pull request by agitator**
Fix https://github.com/plone/Products.CMFPlone/issues/2848

### CODE REVIEW

**Comment by pbauer** [comment]
@agitator this does not fully fix the issue. See my comments and screenshots in the ticket.

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Comment by agitator** [comment]
@pbauer fixed the length of the submenu, please check

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
