### PR TITLE
limited printed data to page content only #139

### PR DESCRIPTION
**Pull request by enkidulan**
fix for #139
limited printed data to page content area only 
print_page_edited

### CODE REVIEW

**Comment by jensens** [comment]
may you

- fix the merge conflict
- apply this to master, as well

thanks!

**Comment by enkidulan** [comment]
I've fixed the merge conflict. 
Applying this fix for master will require some more work and currently I'm a bit short on time, so I cannot promise anything.

**Comment by enkidulan** [comment]
@jensens can I somehow to help to speed up the process of accepting this PR and also #135 and #136 into master and releasing new `1.6.24` version of plonetheme.barceloneta?

**Comment by thet** [comment]
I did a forward port in https://github.com/plone/plonetheme.barceloneta/pull/143

**Pull request merged**
