### PR TITLE
Date-Time widget  fixes referencing issue 891 from Products.CMFPlone

### PR DESCRIPTION
**Pull request by ichim-david**
With the css changes that I've made the date widget looks like this for german language:
date-widget-changes
We could go back to the large buttons for the footer but I think we made better use of the space with the
current styles where the buttons are only 33% instead of 50:
date-picker-fixes-with-large-buttons

I can amend my fixes with any extra suggestions of course.

### CODE REVIEW

**Comment by ichim-david** [comment]
Due to so many other issues I am going ahead and I will merge these fixes.
The widget already looks a lot better than before these fixes and any extra bugs it might bring I
pledge to fix if they are added.

**Comment by pbauer** [comment]
great!

**Comment by ichim-david** [comment]
and here is another screenshot with how the widget looked before the changes from this ticket
before-merge

**Comment by vangheem** [comment]
Thank you. So glad someone is taking care of these annoying UI issues.

**Pull request merged**
