### PR TITLE
Structural fixes

### PR DESCRIPTION
**Pull request by tmassman**
This PR fixes the current content column and footer implementation.

The current Footer is build on top of footer portlets. But adding additional portlets to the footer will result in a messy and unstyled footer:

footer before

With some XSLT and a little bit of CSS we are able to create a doormat like footer with up to 4 columns (1 portlet: 12 col width 2 portlets: 6 cols, 3 portlets: 4 cols, 4 portlets: 3 cols and more than 4 portlets: 3 cols each), based on the underlying bootstrap grid:

footer with doormat

The content columns are currently in the "wrong" order in the HTML: column 1 comes before the main content column, which makes it hard to style for mobile views (portlet columns (sidebars) should come at the very end). Bootstrap gives us the option to move columns around, but the order needs to be changed to be able to have all sidebar columns below the main content on mobile width screens.

If both portlet columns are available, they will be shown next to each-other on small screens, and stacked on top of each-other on smallest screens:
3 columns small

3 columns smallest

On desktop wide screens, columns will be shown in the classic 3-column layout:
3 columns desktop

### CODE REVIEW

**Comment by tmassman** [comment]
#160

**Comment by jensens** [comment]
this is planned for 5.2 only right? so we need to branch away for 5.1.

**Comment by tmassman** [comment]
Those changes are safe for 5.1.x and 5.2.x (even 5.0.x).

**Comment by tmassman** [comment]
@MrTango could you please take a look at the failing 5.2 tests?

**Pull request merged**
